name: restrosupply
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  go_router: ^14.1.4
  google_maps_flutter: ^2.7.0
  flutter_config: ^2.0.2
  http: ^1.2.1
  qr_flutter: ^4.1.0
  flip_card: ^0.7.0
  flutter_login: ^5.0.0
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  provider: ^6.1.2
  firebase_storage: ^12.0.1
  html: ^0.15.4
  file_picker: ^8.0.5
  url_launcher: ^6.3.0
  cloud_firestore: ^5.1.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3
  flutter_stripe: ^10.2.0
  flutter_credit_card: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/
    - assets/FoilContainerandLid/
    - assets/PaperCoffeeCupandLid/
    - assets/PaperSoupCupsandLid/
    - assets/PlasticBag/
    - assets/BondorThermalPaperRoll/
    - assets/WoodTableware/
    - assets/PlasticPortionCups/
    - assets/PlasticBag/
    - assets/PaperCoffeeCupandLid/
    - assets/PaperShoppingBag/
    - assets/SugarcaneCompostableProducts/
    - assets/category/

  uses-material-design: true
