import 'package:restrosupply/constants.dart';

// these names will show in category page
const String baggage = "Sugarcane Compostable Products";
const String kraft = "Kraft Paper Fold Box";
const String aluminum = "Foil Container and Lid";
const String shopping = "Paper Shopping Bag";
const String coffee = "Paper Coffee cup and Lid";
const String soup = "Paper Soup cup and lid";
const String plastic = "Plastic Bags";
const String thermal = "Bond or Thermal Paper Roll";
const String napkin = "Napkin";
const String portion = "Plastic Portion cups";
const String wood = "Wood Tableware";

Map<String, Map<String, List<List<dynamic>>>> dataList = {
  "Bagasse Products": {
    "data": [
      [
        " Chartland - 6\" - Bagasse Square Plate ",
        "",
        true,
        true,
        true,
        "Chartland - 6\" - Bagasse Square Plate",
      ],
      [
        " Chartland - 8X8-3 Compartment Bagasse Brown Clamshell Container ",
        "assets/SugarcaneCompostableProducts/hi.png",
        true,
        true,
        true,
        "Chartland - 8X8-3 Compartment Bagasse Brown Clamshell Container",
      ],
      [
        " Chartland - Bagasse Brown Container with plastic lid - 32oz - 1 Comb ",
        "assets/SugarcaneCompostableProducts/3.png",
        true,
        true,
        true,
        "Chartland - Bagasse Brown Container with plastic lid - 32oz - 1 Comb",
      ],
      [
        " Chartland - 9\"-3 Compartment Bagasse Plates - 500ct/CS ",
        "assets/SugarcaneCompostableProducts/4.png",
        true,
        true,
        true,
        "PO#: 20012",
        "Pacing: 10X50 CT",
      ],
      [
        " Chartland - 9X9 - 3 Compartment Bagasse Light Brown Clamshell Container ",
        "assets/SugarcaneCompostableProducts/5.png",
        true,
        true,
        true,
        "Chartland - 9X9 - 3 Compartment Bagasse Light Brown Clamshell Container",
      ],
      [
        " Golden Maple - Clear Lid For 24/32oz Bagasse Round Bowl - 600ct/CS ",
        "assets/SugarcaneCompostableProducts/6.png",
        true,
        true,
        true,
        "PO#: 20039",
        "Packing: 12X50 CT",
      ],
      [
        " Chartland - 9X6 Bagasse Clamshell Container - 200ct/CS ",
        "assets/SugarcaneCompostableProducts/7.png",
        true,
        true,
        true,
        "PO#: 20025",
        "Packing: 4X50 CT",
      ],
      [
        " Chartland - 10\" - 3 Compartment Bagasse Plates ",
        "assets/SugarcaneCompostableProducts/8.png",
        true,
        true,
        true,
        "Chartland - 10\" - 3 Compartment Bagasse Plates",
      ],
      [
        " Chartland - Bagasse Brown Container with plastic lid - 28oz - 1 Comb - 150ct/CS ",
        "assets/SugarcaneCompostableProducts/9.png",
        true,
        true,
        true,
        "PO#: 20003",
        "Packing: 3X50 CT",
      ],
      [
        " Chartland - 10\" - 3 Compartment Bagasse Light Brown Plates - 200ct/CS ",
        "",
        true,
        true,
        true,
        "PO#: 20014H",
      ],
      [
        " Chartland - 9\" - 3 Compartment Bagasse Light Brown Plates ",
        "",
        true,
        true,
        true,
        "Chartland - 9\" - 3 Compartment Bagasse Light Brown Plates",
      ],
      [
        " Chartland - 12.5\" - Bagasse Oval Plate - 500ct/CS ",
        "",
        true,
        true,
        true,
        "PO#: 20016",
        "Packing: 10X50 CT",
      ],
      [
        " Chartland - 8X8 Bagasse Brown Clamshell Container ",
        "assets/SugarcaneCompostableProducts/13.png",
        true,
        true,
        true,
        "Chartland - 8X8 Bagasse Brown Clamshell Container",
      ],
      [
        " Chartland - 8\"- Bagasse Square Plate - 1000ct/CS ",
        "",
        true,
        true,
        true,
        "PO#: 20018",
        "Packing: 20X50 CT",
      ],
      [
        " Chartland - 7\" Bagasse Plates ",
        "assets/SugarcaneCompostableProducts/15.png",
        true,
        true,
        true,
        "Chartland - 7\" Bagasse Plates",
      ],
      [
        " Chartland - 8.5X8.5 -1  Bagasse Light Brown Clamshell Container ",
        "assets/SugarcaneCompostableProducts/16.png",
        true,
        true,
        true,
        "Chartland - 8.5X8.5 -1\u00a0 Bagasse Light Brown Clamshell Container",
      ],
      [
        " Golden Maple - 48oz Round Bowl - Bagasse - 300ct/CS ",
        "assets/SugarcaneCompostableProducts/17.png",
        true,
        true,
        true,
        "PO#: 20041",
        "Packing: 6X50 CT",
      ],
      [
        " Chartland - Bagasse Brown Container with plastic lid - 24 oz - 2 Comb - 150ct/CS ",
        "",
        true,
        true,
        true,
        "PO#: 20002",
        "Packing: 3X50 CT",
      ],
      [
        " Chartland - 9X6 - 2 Compartment Bagasse Light Brown Clamshell Container - 200ct/CS ",
        "",
        true,
        true,
        true,
        "PO#:20026H",
        "Packing: 4X50 CT",
      ],
      [
        " Chartland - Bagasse Brown Container with plastic lid - 28oz - 2 Comb ",
        "assets/SugarcaneCompostableProducts/20.png",
        true,
        true,
        true,
        "Chartland - Bagasse Brown Container with plastic lid - 28oz - 2 Comb",
      ],
      [
        " Chartland - 9X9 Bagasse Clamshell Container - 200ct/CS ",
        "assets/SugarcaneCompostableProducts/21.png",
        true,
        true,
        true,
        "PO#: 20027",
        "Packing: 4X50 CT",
      ],
      [
        " Chartland - 10\" - Bagasse Square Plate - 500ct/CS ",
        "",
        true,
        true,
        true,
        "PO#: 20019",
        "Packing: 10X50 CT",
      ],
      [
        " Chartland - 9\" Bagasse Light Brown Plates ",
        "assets/SugarcaneCompostableProducts/23.png",
        true,
        true,
        true,
        "Chartland - 9\" Bagasse Light Brown Plates",
      ],
      [
        " Chartland - 9X9 - 3 Compartment Bagasse Clamshell Container - 200ct/CS ",
        "assets/SugarcaneCompostableProducts/24.png",
        true,
        true,
        true,
        "PO#: 20028",
        "Packing: 4X50 CT",
      ],
      [
        " Chartland - 9X6 - 2 Compartment Bagasse Clamshell Container ",
        "assets/SugarcaneCompostableProducts/25.png",
        true,
        true,
        true,
        "Chartland - 9X6 - 2 Compartment Bagasse Clamshell Container",
      ],
      [
        " Chartland - 10\" Bagasse Plates ",
        "assets/SugarcaneCompostableProducts/26.png",
        true,
        true,
        true,
        "Chartland - 10\" Bagasse Plates",
      ],
      [
        " Chartland - Bagasse Brown Container with plastic lid - 32oz - 2 Comb - 150ct/CS ",
        "assets/SugarcaneCompostableProducts/27.png",
        true,
        true,
        true,
        "PO#: 20006",
        "Packing: 3X50 CT",
      ],
      [
        " Chartland - 6\" Bagasse Plates ",
        "assets/SugarcaneCompostableProducts/28.png",
        true,
        true,
        true,
        "Chartland - 6\" Bagasse Plates",
      ],
      [
        " Chartland - 8\" - Bagasse Light Brown Square Plate ",
        "",
        true,
        true,
        true,
        "Chartland - 8\" - Bagasse Light Brown Square Plate",
      ],
      [
        " Chartland - 8.5X8.5 Bagasse Clamshell Container - 200ct/CS ",
        "assets/SugarcaneCompostableProducts/30.png",
        true,
        true,
        true,
        "PO#: 20024",
        "Packing: 4X50 CT",
      ],
      [
        " Chartland - 7\"X5.5\"X2.8\" Bagasse Light Brown Clamshell Container ",
        "",
        true,
        true,
        true,
        "Chartland - 7\"X5.5\"X2.8\" Bagasse Light Brown Clamshell Container",
      ],
      [
        " Golden Maple - 16oz Round Bowl - Bagasse - 600ct/CS ",
        "assets/SugarcaneCompostableProducts/32.png",
        true,
        true,
        true,
        "Golden Maple - 16oz Round Bowl - Bagasse - 6X100CT/CS",
        "Packing: 12X50 CT",
      ],
      [
        " Chartland - 8X8 - 3 Compartment Bagasse Clamshell Container ",
        "assets/SugarcaneCompostableProducts/33.png",
        true,
        true,
        true,
        "Chartland - 8X8 - 3 Compartment Bagasse Clamshell Container",
      ]
    ],
    catImage: [
      ["assets/category/baggage.webp", baggage]
    ]
  },
  "Kraft Paper Fold Box": {
    data: [
      [
        "Wisdom - #8 Kraft Paper Fold Box - 40X50ct/CS",
        "",
        true,
        true,
        true,
        "PO#: 90008",
        "Packing: 4X50ct"
      ],
      [
        "Wisdom - #1 Kraft Paper Fold Box - 40X50ct/CS",
        "",
        true,
        true,
        true,
        "PO#: 90001",
        "Packing: 4X50ct"
      ],
      [
        "Wisdom - #2 Kraft Paper Fold Box - 40X50ct/CS",
        "",
        true,
        true,
        true,
        "PO#: 90002",
        "Packing: 4X50ct"
      ],
      [
        "Wisdom - #4 Kraft Paper Fold Box - 40X40ct/CS",
        "",
        true,
        true,
        true,
        "Wisdom-#4 Kraft Paper Fold Box",
        "Packing: 4X40ct"
      ],
      [
        "Wisdom - #3 Kraft Paper Fold Box - 40X50ct/CS",
        "",
        true,
        true,
        true,
        "PO#: 90003",
        "Packing: 4X50ct"
      ],
    ],
    catImage: [
      ["assets/category/kraft.webp", kraft]
    ]
  },
  "Aluminum Foil": {
    data: [
      [
        " Chartland - Full Size Lid For Aluminium Steam Pan - Little Packing - 100ct/CS ",
        "",
        true,
        true,
        true,
        "PO#  10045",
        "Packing: 20X5ct",
      ],
      [
        " Chartland - Foil Laminated Lid for 1.5 LB Oblong - HZJ310LH ",
        "assets/FoilContainerandLid/-5067629789285023182.png",
        true,
        true,
        true,
        "PO#  10020",
        "",
      ],
      [
        " Chartland - Plastic Dome Lid For 1 lb Oblong Container 500ps -HZJ300LD ",
        "assets/FoilContainerandLid/1530432896468087288.png",
        true,
        true,
        true,
        "PO#  10016",
        "Packing: 500ct/CS",
      ],
      [
        " Chartland - Foil Laminated Lid for 2.5 LB Oblong - HZJ320LH ",
        "assets/FoilContainerandLid/7656599161876728874.png",
        true,
        true,
        true,
        "PO#  10023",
        "Packing: 500ct/cs",
      ],
      [
        " Chartland - Foil - 8''  Heavy Round  - Aluminium Foil Container - HZJ208H ",
        "assets/FoilContainerandLid/-3415642595002051157.png",
        true,
        true,
        true,
        "PO#  10007",
        "Packing: 500ct/CS",
      ],
      [
        " Chartland - Foil Full Size Deep - Aluminium Steam Pan - HZJ520 ",
        "assets/FoilContainerandLid/1255525702905351835.png",
        true,
        true,
        true,
        "PO#  10030",
        "Packing: 50ct/cs",
      ],
      [
        " Chartland - Foil - 2.5 lb Oblong - Aluminium Foil Container - HZJ320 ",
        "assets/FoilContainerandLid/-2103550421259601792.png",
        true,
        true,
        true,
        "PO#  10021",
        "Packing: 500ct/CS",
      ],
      [
        " Chartland - Foil -12\" Aluminum Foil Roll  -Heave - 200M - HZJ1220H ",
        "",
        true,
        true,
        true,
        "Chartland-Foil-12\" Aluminum Foil-Heave-200M",
        "",
      ],
      [
        " Chartland - Foil Half Size Medium - Aluminium Steam Pan - HZJ410 ",
        "assets/FoilContainerandLid/-8030245296767403527.png",
        true,
        true,
        true,
        "Chartland - Foil Half Size Medium - Aluminium Steam Pan - HZJ410",
        "Packing: 100ct/CS",
      ],
      [
        " Chartland - Foil Laminated Lid for 1 LB Oblong - HZJ300LH ",
        "assets/FoilContainerandLid/6347262693758708240.png",
        true,
        true,
        true,
        "Chartland - Foil Laminated Lid for 1 LB Oblong - HZJ300LH",
        "Packing: 500ct/CS",
      ],
      [
        " Chartland - Foil Full Size Shallow - Aluminium Steam Pan - HZJ500 ",
        "assets/FoilContainerandLid/-1110505155769785803.png",
        true,
        true,
        true,
        "Chartland - Foil Full Size Shallow - Aluminium Steam Pan - HZJ500",
        "PO#: 10028Packing: 50 CtCs / Skids For 53\" Trailer: 70 Cs",
      ],
      [
        " Chartland - Plastic Dome Lid For 2.25 lb Oblong Container 500ps - HZJ320LD ",
        "assets/FoilContainerandLid/-1310506819108450046.png",
        true,
        true,
        true,
        "Chartland-Dome Lids for 1.5 lb Oblong Pan - Clear",
        "Packing: 500ct/CS",
      ],
      [
        " Chartland - Half Size Lid For Aluminium Steam Pan - HZJ400L ",
        "assets/FoilContainerandLid/6711033363432196810.png",
        true,
        true,
        true,
        "PO#  10027",
        "Packing: 500ct/CS",
      ],
      [
        " Chartland - Foil Half Size Deep - Aluminium Steam Pan - HZJ420 ",
        "assets/FoilContainerandLid/8215789381350695195.png",
        true,
        true,
        true,
        "PO#  10026",
        "Packing: 100ct/CS",
      ],
      [
        " Chartland - Foil - 9\" Round - Plastic Dome  Lid - HZJ209LD ",
        "assets/FoilContainerandLid/6680531210793237110.png",
        true,
        true,
        true,
        "PO#:10014",
        "Packing: 500ct/CS",
      ],
      [
        " Chartland - Foil - 7\" Foil Laminated Board Lid - HZJ207LH ",
        "assets/FoilContainerandLid/8021845946169151237.png",
        true,
        true,
        true,
        "PO#  10005",
        "Packing: 500ct/CS",
      ],
      [
        " Chartland - Foil - 1 lb Oblong-Aluminium Foil Container - HZJ300 ",
        "assets/FoilContainerandLid/-1093848701009628569.png",
        true,
        true,
        true,
        "PO#  10015",
        "Packing: 500ct/CS",
      ],
      [
        " Chartland - Foi l-18\" Aluminum Foil Roll - Standard -18\"X100M - HZJ1810 ",
        "",
        true,
        true,
        true,
        "PO#  10036",
        "Packing: 6 Rolls/CS",
      ],
      [
        " Chartland - Foil - 9\" Foil Laminated Board Lid - HZJ209LH ",
        "assets/FoilContainerandLid/-1738084204047814998.png",
        true,
        true,
        true,
        "PO#  10013",
        "Packing: 500ct/CS",
      ],
      [
        " Chartland - Foil - 8\"Round Foil Laminated Board Lid - HZJ208LH ",
        "assets/FoilContainerandLid/-1075690813294322601.png",
        true,
        true,
        true,
        "PO#  10009",
        "Packing: 500ct/CS",
      ],
      [
        " Chartland - Aluminium Rectangle Steam Pan - 4332 - 50ct/CS ",
        "assets/FoilContainerandLid/4241294205298748341.png",
        true,
        true,
        true,
        "PO#: 10046",
        "Packing: 50ct/CS",
      ],
      [
        " Chartland - Half Size Lid For Aluminium Steam Pan - Little Packing - 400ct/CS ",
        "",
        true,
        true,
        true,
        "PO#  10044",
        "Packing: 40X10ct",
      ],
      [
        " Chartland - Foil Half Size Medium - Aluminium Steam Pan - Little Packing - 100ct/CS ",
        "assets/FoilContainerandLid/5472468513865358023.png",
        true,
        true,
        true,
        "PO#  10040",
        "Packing: 10X10ctPO#:: 10039",
      ],
      [
        " Chartland - Foil Half Size Deep - Aluminium Steam Pan - Little Packing - 100ct/CS ",
        "assets/FoilContainerandLid/-6109089530879734048.png",
        true,
        true,
        true,
        "PO#  10040",
        "Packing: 10X10ct",
      ],
      [
        " Chartland - Foil Full Size Deep - Aluminium Steam Pan - Little Packing -50ct/CS ",
        "assets/FoilContainerandLid/2092562085299589936.png",
        true,
        true,
        true,
        "PO#  10043",
        "Packing: 10X5ct",
      ],
      [
        " Chartland - Foil Full Size Medium - Aluminium Steam Pan - Little Packing - 50ct/CS ",
        "",
        true,
        true,
        true,
        "PO# : 10042",
        "Packing: 10X5ct",
      ],
      [
        " Roaster Pans/Oval Pan - HZJ - 4399 - 100ct/CS ",
        "",
        true,
        true,
        true,
        "Roaster Pans/Oval Pan-HZJ-4399",
        "Packing: 50ct/CS",
      ],
      [
        " Chartland - Roaster Pans/Oval Pan - HZJ - 7500 - 50ct/CS ",
        "assets/FoilContainerandLid/8947007543715341845.png",
        true,
        true,
        true,
        "PO# : 10047",
        "Packing: 50ct/CS",
      ],
      [
        " Chartland - Plastic Dome Lid For 1.5lb Oblong Container 500ps -HZJ310LD ",
        "assets/FoilContainerandLid/-3002679085674920573.png",
        true,
        true,
        true,
        "PO# : 10019",
        "Packing: 500ct/CS",
      ],
      [
        " Chartland - Plastic Dome Lid For Half Size Foil Pan -100pcs - HZJ400LD ",
        "assets/FoilContainerandLid/2902447806978067505.png",
        true,
        true,
        true,
        "PO#  10047",
        "Packing: 100ct/CS",
      ],
      [
        " Chartland - Foil Full Size Medium - Aluminium Steam Pan - HZJ510 ",
        "assets/FoilContainerandLid/-4500196639674879397.png",
        true,
        true,
        true,
        "PO#  10029",
        "Packing: 50ct/CS",
      ],
      [
        " Chartland - Foil - 7 '- Heavy-'Round - Aluminium Foil Container - HZJ207H ",
        "assets/FoilContainerandLid/3996725390460646488.png",
        true,
        true,
        true,
        "PO#  10002",
        "Packing: 500ct/cs",
      ],
      [
        " Chartland - Foil -12\" Aluminum Foil Roll - Standard - 12\"X200M - HZJ1220 ",
        "",
        true,
        true,
        true,
        "PO#  10034",
        "Packing: 6 Rolls/CS",
      ],
      [
        " Chartland - Foil - 8\" Round - Plastic Dome  Lid - HZJ208LD ",
        "assets/FoilContainerandLid/-211806971462013436.png",
        true,
        true,
        true,
        "PO#  10010",
        "Packing: 500ct/CS",
      ],
      [
        " Chartland - Full Size Lid For Aluminium Steam Pan - HZJ500L ",
        "assets/FoilContainerandLid/452735009445000207.png",
        true,
        true,
        true,
        "PO#  10031",
        "Packing: 50ct/CS",
      ],
      [
        " Chartland - Foil - 7 '- Standard Round - Aluminium Foil Container - HZJ207 ",
        "assets/FoilContainerandLid/-7065069904968209680.png",
        true,
        true,
        true,
        "PO#  10002",
        "Packing: 500ct/CsWeight: 7.5g",
      ],
      [
        " Chartland - Foil - 9' Heavy Round - Aluminium Foil Container - HZJ209H ",
        "assets/FoilContainerandLid/2538429122435449628.png",
        true,
        true,
        true,
        "PO#  10011",
        "Packing: 500ct/CS",
      ],
      [
        " Chartland - Foil -18\" Aluminum Foil Roll - Heave -18\"X100M - HZJ1810H ",
        "",
        true,
        true,
        true,
        "PO#  10037",
        "Packing: 6 Rolls/CS",
      ],
      [
        " Chartland - Foil Half Size Shallow - Aluminium Steam Pan - HZJ400 ",
        "assets/FoilContainerandLid/-249417970706165275.png",
        true,
        true,
        true,
        "PO#  10024",
        "Packing: 100ct/CS",
      ],
      [
        " Chartland - Foil - 1.5 lb Oblong - Aluminium Foil Container - HZJ310 ",
        "assets/FoilContainerandLid/-1027191170826474963.png",
        true,
        true,
        true,
        "PO#  10018",
        "Packing: 500ct/CS",
      ]
    ],
    catImage: [
      ["assets/category/aluminum.webp", aluminum]
    ]
  },
  "Paper Shopping Bag": {
    data: [
      [
        " Golden Maple - (Super Strong) Kraft Paper Bags with Twisted Handles - 10X6X13 - 250ct/CS ",
        "assets/PaperShoppingBag/-1918688910506603471.png",
        true,
        true,
        true,
        "Golden Maple - (Super Strong)\u00a0Kraft Paper Handle Bag -10\"X6.5\"X12\"-250 ct",
        "Packing: 250ct/CS",
        "Paper Bags"
      ],
      [
        " Golden Maple - (Super Strong) Kraft Paper Bags with Twisted Handles - 13X7X17 - 200ct/CS ",
        "assets/PaperShoppingBag/6792400537161498743.png",
        true,
        true,
        true,
        "Golden Maple - (Super Strong)\u00a0Kraft Paper Bags with Twisted Handles - 13X7X17",
        "Packing: 200ct/CS",
        "Paper Bags"
      ],
      [
        " Golden Maple - (Super Strong) White Paper Bags with Twisted Handles - 10X6X13 - 250ct/CS ",
        "assets/PaperShoppingBag/-9004487357085058787.png",
        true,
        true,
        true,
        "PO#: PB009W",
        "Packing: 250ct/CS",
        "Paper Bags"
      ],
      [
        " Golden Maple - (Super Strong) Kraft Paper Bags with Twisted Handles - 13X7X13 - 200ct/CS ",
        "assets/PaperShoppingBag/-3968352626926764221.png",
        true,
        true,
        true,
        "Golden Maple - (Super Strong)\u00a0Kraft Paper Bags with Twisted Handles - 13X7X13",
        "Packing: 200ct/CS",
        "Paper Bags"
      ],
      [
        " Golden Maple - (Super Strong)  Paper Bags with Twisted Handles -White - 13X7X17 - 200ct/CS ",
        "assets/PaperShoppingBag/7645501136332211547.png",
        true,
        true,
        true,
        "PO#: PB011W",
        "Packing: 200ct/CS",
        "Paper Bags"
      ],
      [
        " Golden Maple -  Kraft Paper Bags with Twisted Handles - 10X6X13 - 250ct/CS ",
        "assets/PaperShoppingBag/-7672088551004513088.png",
        true,
        true,
        true,
        "PO#: PB003",
        "Packing: 250ct/CS",
        "Paper Bags"
      ],
      [
        " Golden Maple - (Super Strong) White Paper Bags with Twisted Handles - 8X4.5X10.6 - 250ct/CS ",
        "assets/PaperShoppingBag/8546618619284421840.png",
        true,
        true,
        true,
        "PO#: PB008W",
        "Packing: 250ct/CS",
        "Paper Bags"
      ],
      [
        " Golden Maple -  Kraft Paper Bags with Twisted Handles - 13X8.5X13 - 250ct/CS ",
        "assets/PaperShoppingBag/2708982093779888984.png",
        true,
        true,
        true,
        "PO# PB004",
        "Packing: 250ct/CS",
        "Paper Bags"
      ],
      [
        " Golden Maple - (Super Strong) Kraft Paper Bags with Twisted Handles - 8X4.5X10.6 - 250ct/CS ",
        "assets/PaperShoppingBag/6651280695903989693.png",
        true,
        true,
        true,
        "PO#: PB001S",
        "Packing: 250ct/CS",
        "Paper Bags"
      ],
      [
        " Golden Maple -  Kraft Paper Bags with Twisted Handles - 13X7X17 - 250ct/CS ",
        "assets/PaperShoppingBag/-8047310861267980810.png",
        true,
        true,
        true,
        "PO#: PB006",
        "Packing: 250ct/CS",
        "Paper Bags"
      ],
      [
        " Golden Maple - (Super Strong) White Paper Bags with Twisted Handles - 13X7X13 -200ct/CS ",
        "assets/PaperShoppingBag/9164454087588030262.png",
        true,
        true,
        true,
        "PO#: PB010W",
        "Packing: 200ct/CS",
        "Paper Bags"
      ]
    ],
    catImage: [
      ["assets/category/shopping.webp", shopping]
    ]
  },
  "Paper Coffee cup": {
    data: [
      [
        " Golden Maple - 8oz Ripple Wall Paper Cups - 1000ct/CS ",
        "assets/PaperCoffeeCupandLid/-2827500280028018178.png",
        true,
        true,
        true,
        "PO#: 30014",
        "Packing: 20X50 CT",
      ],
      [
        " Golden Maple - 10 - 24 oz Kraft Sleeve For Hot Paper Cups - 1000ct/cs ",
        "assets/PaperCoffeeCupandLid/-6045891955566277026.png",
        true,
        true,
        true,
        "PO#: 30012",
        "Packing: 1000 CT",
      ],
      [
        " Golden Maple - 10oz Ripple Wall Paper Cups - 500ct/CS ",
        "assets/PaperCoffeeCupandLid/7008639498803102390.png",
        true,
        true,
        true,
        "PO#: 30015",
        "Packing: 20X25 CT",
      ],
      [
        " Golden Maple - 7 oz Paper Cup - Printed - 3000ct/CS ",
        "assets/PaperCoffeeCupandLid/9129364089255799879.png",
        true,
        true,
        true,
        "PO#: 30023",
        "Packing:: 60X50CT",
      ],
      [
        " Golden Maple - 20 oz White  Paper Cups - 1000ct/CS ",
        "assets/PaperCoffeeCupandLid/9193451214144446244.png",
        true,
        true,
        true,
        "PO#: 30024",
        "Packing: 20X50 CT",
      ],
      [
        " Golden Maple - 4oz Paper Cup - Printed - 1000ct/CS ",
        "assets/PaperCoffeeCupandLid/5290209890624805297.png",
        true,
        true,
        true,
        "PO#: 30006",
        "Packing: 20X50 CT",
      ],
      [
        " Golden Maple - 4oz White Hot Paper Cups - 1000ct/CS ",
        "assets/PaperCoffeeCupandLid/7004026186944813999.png",
        true,
        true,
        true,
        "PO#: 30001",
        "",
      ],
      [
        " Golden Maple - 10oz Paper Cups - Printed - 1000ct/CS ",
        "assets/PaperCoffeeCupandLid/-2825072995049149939.png",
        true,
        true,
        true,
        "PO#: 30008",
        "Packing: 20X50 CT",
      ],
      [
        " Golden Maple - 12oz Ripple Wall Paper Cups - 500ct/CS ",
        "assets/PaperCoffeeCupandLid/7337705008364489869.png",
        true,
        true,
        true,
        "PO#: 30016",
        "Packing: 20X25ct",
      ],
      [
        " Golden Maple - White Flat Lid for 10-20oz Cup - 1000ct/CS ",
        "assets/PaperCoffeeCupandLid/7729853231948428237.png",
        true,
        true,
        true,
        "PO#: 30022",
        "Packing: 20X50 CT",
      ],
      [
        " Golden Maple - 8oz Paper Cups - Printed - 1000ct/CS ",
        "assets/PaperCoffeeCupandLid/-324553280787597343.png",
        true,
        true,
        true,
        "PO#: 30007",
        "Packing: 20X50 CT",
      ],
      [
        " Golden Maple -16oz Paper Cup - White - 1000ct/CS ",
        "assets/PaperCoffeeCupandLid/-7548750451900188014.png",
        true,
        true,
        true,
        "PO#30005",
        "Packing: 20X50 CT",
      ],
      [
        " Golden Maple - Black Dome Tear Lid for 10-20oz Paper Cup - 1000ct/CS ",
        "assets/PaperCoffeeCupandLid/-1001736913267167441.png",
        true,
        true,
        true,
        "PO#: 30020",
        "Packing: 20X50 CT",
      ],
      [
        " Golden Maple-10 oz White Paper Cup - 1000ct/CS ",
        "assets/PaperCoffeeCupandLid/1360314386928355401.png",
        true,
        true,
        true,
        "PO#: 30003",
        "Packing: 20X50 CT",
      ],
      [
        " Golden Maple - White Dome Lid for 8oz Paper Cup - 1000ct/CS ",
        "assets/PaperCoffeeCupandLid/2891123925828032781.png",
        true,
        true,
        true,
        "PO#: 30019",
        "Packing: 20X50 CT",
      ],
      [
        " Golden Maple - 16oz Paper Cup - Printed - 1000ct/CS ",
        "assets/PaperCoffeeCupandLid/-2777578630649795407.png",
        true,
        true,
        true,
        "PO#: 30010",
        "Packing: 20X50 CT",
      ],
      [
        " Golden Maple-Rapple 16oz Hot Paper Cups - 500ct/CS ",
        "assets/PaperCoffeeCupandLid/8512632283701271388.png",
        true,
        true,
        true,
        "PO#: 30017",
        "Packing: 20X25CT",
      ],
      [
        " Golden Maple - 12 oz White Paper Cup - 1000ct/CS ",
        "assets/PaperCoffeeCupandLid/9129499862199864207.png",
        true,
        true,
        true,
        "PO#: 30004",
        "Packing: 20X50 CT",
      ],
      [
        " Golden Maple - 12oz Paper Cups - Printed - 1000ct/CS ",
        "assets/PaperCoffeeCupandLid/6534028848943984860.png",
        true,
        true,
        true,
        "PO#: 30009",
        "Packing: 20X50 CT",
      ],
      [
        " Golden Maple - White Dome  Lid for 4oz Paper Cup - 1000ct/CS ",
        "assets/PaperCoffeeCupandLid/-6518806071820155666.png",
        true,
        true,
        true,
        "PO#: 30018",
        "Packing: 20X50 CT",
      ],
      [
        " Golden Maple - 8oz White Paper Cup - 1000ct/CS ",
        "assets/PaperCoffeeCupandLid/-3887111517877199892.png",
        true,
        true,
        true,
        "PO#: 30002",
        "Packing: 20X50 CT",
      ],
      [
        " Golden Maple - White Flat Lid for 8 oz Cup - 1000ct/CS ",
        "assets/PaperCoffeeCupandLid/4123313158291754915.png",
        true,
        true,
        true,
        "PO#: 30021",
        "Packing: 20X50 CT",
      ]
    ],
    catImage: [
      ["assets/category/coffee.webp", coffee]
    ]
  },
  "Paper Soup cup": {
    data: [
      [
        " Golden Maple - 24 oz Paper Soup Container - Printed - 500ct/CS ",
        "assets/PaperSoupCupsandLid/-2879818427039569693.png",
        true,
        true,
        true,
        "PO#: 40009",
        "Packing: 20X25CT",
      ],
      [
        " Golden Maple - Plastic Lid for 8 oz Paper Soup Container - 1000ct/CS ",
        "assets/PaperSoupCupsandLid/9048935433622729636.png",
        true,
        true,
        true,
        "PO#: 40013",
        "Packing: 20X50ct",
      ],
      [
        " Golden Maple - 8 oz Paper Soup Container - White - 500ct/CS ",
        "assets/PaperSoupCupsandLid/-6595210785455372051.png",
        true,
        true,
        true,
        "PO#: 40001",
        "Packing: 20X50CT",
      ],
      [
        " Golden Maple - Plastic Lid for 12 - 32 oz Paper Soup Container - 500ct/CS ",
        "assets/PaperSoupCupsandLid/5074271727679824436.png",
        true,
        true,
        true,
        "PO#: 40014",
        "Packing: 20X25ct",
      ],
      [
        " Golden Maple - 16 oz Paper Soup Container - White - 500ct/CS ",
        "assets/PaperSoupCupsandLid/7390367085374610721.png",
        true,
        true,
        true,
        "PO#: 40003",
        "Packing: 20X25ct",
      ],
      [
        " Golden Maple - 12 oz Paper Soup Container - Printed - 500ct/CS ",
        "assets/PaperSoupCupsandLid/1941649926967125938.png",
        true,
        true,
        true,
        "PO#: 40007",
        "Packing: 20X25CT",
      ],
      [
        " Golden Maple - 12 oz Paper Soup Container - White - 500ct/CS ",
        "assets/PaperSoupCupsandLid/518355019384328911.png",
        true,
        true,
        true,
        "PO#40002",
        "Packing: 20X25CT",
      ],
      [
        " Golden Maple - Plastic Lid for 4 oz Paper Soup Container ",
        "assets/PaperSoupCupsandLid/-8192734206076534844.png",
        true,
        true,
        true,
        "Golden Maple - Plastic Lid for 4 oz Paper Soup Container",
        "",
      ],
      [
        " Golden Maple - 8 oz Paper Soup Container - Printed - 1000ct/CS ",
        "assets/PaperSoupCupsandLid/6383480510946553017.png",
        true,
        true,
        true,
        "PO#: 40006",
        "Packing: 20X50CT",
      ],
      [
        " Golden Maple - 24 oz Paper Soup Container - White - 500ct/CS ",
        "assets/PaperSoupCupsandLid/8603218435935191542.png",
        true,
        true,
        true,
        "PO#40004",
        "Packing: 20X25CT",
      ],
      [
        " Golden Maple - 16 oz Paper Soup Container - Printed - 500ct/CS ",
        "assets/PaperSoupCupsandLid/4144938716270818390.png",
        true,
        true,
        true,
        "PO#: 40008",
        "Packing: 20X25CT",
      ],
      [
        " Golden Maple - 32 oz Paper Soup Container - White - 500ct/CS ",
        "assets/PaperSoupCupsandLid/-2802723693296484639.png",
        true,
        true,
        true,
        "PO#: 40005",
        "Packing: 20X25CT",
      ],
      [
        " Golden Maple -32 oz Paper Soup Container - Printed - 500ct/CS ",
        "",
        true,
        true,
        true,
        "PO#: 40010",
        "Packing: 20X25CT",
      ],
      [
        " Golden Maple - 4 oz Paper Soup Container - White ",
        "assets/PaperSoupCupsandLid/7043751554551887658.png",
        true,
        true,
        true,
        "Golden Maple - 4 oz Paper Soup Container - White",
        "",
      ]
    ],
    catImage: [
      ["assets/category/soup.webp", soup]
    ]
  },
  "Plastic Bags": {
    data: [
      [
        " Poly Bag - 1 lb - 500/Cs ",
        "",
        true,
        true,
        true,
        "Poly Bag - 1 lb - 500/Cs",
      ],
      [
        " Poly Bag - 7 lb - 500/Cs ",
        "assets/PlasticBag/4969809737321870627.png",
        true,
        true,
        true,
        "Poly Bag - 7 lb - 500/Cs",
      ],
      [
        " Poly Bag - 6 lb - 500/Cs ",
        "",
        true,
        true,
        true,
        "Poly Bag - 6 lb - 500/Cs",
      ],
      [
        " Chartland - Garbage Bags - Ex - Strong - 42\" X 48\" - Black ",
        "",
        true,
        true,
        true,
        "Chartland - Garbage Bags - Ex - Strong - 42\" X 48\" - Black",
      ],
      [
        " Golden Maple - Clear 11\"X17\" - Convenient Plastic Rolls - 6X800/Cs ",
        "",
        true,
        true,
        true,
        "Golden Maple - Clear 11\"X17\" - Convenient Plastic Rolls - 6X800/Cs",
      ],
      [
        " Golden Maple - Low Density T - Shirt Bag - White - S4 - 1000/Cs ",
        "",
        true,
        true,
        true,
        "Golden Maple - Low Density T - Shirt Bag - White - S4 - 1000/Cs",
      ],
      [
        " Poly Bag - 2 lb - 500/Cs ",
        "assets/PlasticBag/4631767647430833882.png",
        true,
        true,
        true,
        "Poly Bag - 2 lb - 500/Cs",
      ],
      [
        " Chartland - Garbage Bags - Ex - Strong - 42\" X 48\" - Clear ",
        "",
        true,
        true,
        true,
        "Chartland - Garbage Bags - Ex - Strong - 42\" X 48\" - Clear",
      ],
      [
        " Golden Maple -10.5\"X15.5\" -  Medium Produce Rolls ",
        "",
        true,
        true,
        true,
        "Golden Maple -10.5\"X15.5\" - Medium Produce Rolls",
      ],
      [
        " Chartland - Garbage Bags - Ex - Strong - 35\" X 47\" - Clear ",
        "",
        true,
        true,
        true,
        "Chartland - Garbage Bags - Ex - Strong - 35\" X 47\" - Clear",
      ],
      [
        " Golden Maple -12\"X20\" -  Produce Rolls - Extra Large ",
        "",
        true,
        true,
        true,
        "Golden Maple -12\"X20\" -\u00a0 Produce Rolls - Extra Large",
      ],
      [
        " Chartland - Garbage Bags - Strong - 30\" X 38\" - Clear ",
        "",
        true,
        true,
        true,
        "Chartland - Garbage Bags - Strong - 30\" X 38\" - Clear",
      ],
      [
        " Golden Maple - Low Density T - Shirt Bag - White - S3 - 1000/Cs ",
        "",
        true,
        true,
        true,
        "Golden Maple - Low Density T - Shirt Bag - White - S3 - 1000/Cs",
      ],
      [
        " Golden Maple - Low Density T - Shirt Bag - White - S2 - 2000/Cs ",
        "",
        true,
        true,
        true,
        "Golden Maple - Low Density T - Shirt Bag - White - S2 - 2000/Cs",
      ],
      [
        " Poly Bag - 3 lb - 500/Cs ",
        "assets/PlasticBag/5400092262020302631.png",
        true,
        true,
        true,
        "Poly Bag - 3 lb - 500/Cs",
      ],
      [
        " Chartland - Garbage Bags - Strong - 26\" X 36\" - Black ",
        "",
        true,
        true,
        true,
        "Chartland - Garbage Bags - Strong - 26\" X 36\" - Black",
      ],
      [
        " Chartland - Garbage Bags - Strong - 26\" X 36\" - Clear ",
        "",
        true,
        true,
        true,
        "Chartland - Garbage Bags - Strong - 26\" X 36\" - Clear",
      ],
      [
        " Chartland - Garbage Bags - Ex - Strong - 30\" X 38\" - Clear ",
        "",
        true,
        true,
        true,
        "Chartland - Garbage Bags - Ex - Strong - 30\" X 38\" - Clear",
      ],
      [
        " Poly Bag - 5 lb - 500/Cs ",
        "assets/PlasticBag/-6261716733143437626.png",
        true,
        true,
        true,
        "Poly Bag - 5 lb - 500/Cs",
      ],
      [
        " Poly Bag - 4 lb - 500/Cs ",
        "assets/PlasticBag/6527134580829947406.png",
        true,
        true,
        true,
        "Poly Bag - 4 lb - 500/Cs",
      ],
      [
        " Golden Maple - Clear T - Shirt Rolls (8.25X5X19) - 6X600/Cs ",
        "assets/PlasticBag/-622309803226081206.png",
        true,
        true,
        true,
        "Golden Maple - Clear T - Shirt Rolls (8.25X5X19) - 6X600/Cs",
      ],
      [
        " Poly Bag - 9 lb - 500/Cs ",
        "assets/PlasticBag/3477656146335664397.png",
        true,
        true,
        true,
        "Poly Bag - 9 lb - 500/Cs",
      ],
      [
        " Golden Maple -10.5\"X20\" -  Large Produce Rolls ",
        "",
        true,
        true,
        true,
        "Golden Maple -10.5\"X15.5\" -\u00a0 Large Produce Rolls",
      ],
      [
        " Chartland - Garbage Bags - Strong - 35\" X 47 \"- Black ",
        "",
        true,
        true,
        true,
        "Chartland - Garbage Bags - Strong - 35\" X 47 \"- Black",
      ],
      [
        " Chartland  - Garbage Bags - Strong - 35\" X 47\" - Clear ",
        "",
        true,
        true,
        true,
        "Chartland\u00a0 - Garbage Bags - Strong - 35\" X 47\" - Clear",
      ],
      [
        " Chartland - Garbage Bags - Strong - 30\" X 38\" - Black ",
        "",
        true,
        true,
        true,
        "Chartland - Garbage Bags - Strong - 30\" X 38\" - Black",
      ],
      [
        " Chartland - Garbage Bags - Ragular - 24\" X 22\" - Clear ",
        "",
        true,
        true,
        true,
        "Chartland - Garbage Bags - Ragular - 24 \"X 22\" - Clear",
      ],
      [
        " Chartland - Garbage Bags - Strong - 42\" X 48\" - Clear ",
        "assets/PlasticBag/4521788198660704861.png",
        true,
        true,
        true,
        "Chartland - Garbage Bags - Strong - 42\" X 48\" - Clear",
      ],
      [
        " Golden Maple - Low Density T - Shirt Bag - White - S5 - 1000/Cs ",
        "",
        true,
        true,
        true,
        "Golden Maple - Low Density T - Shirt Bag - White - S5 - 1000/Cs",
      ],
      [
        " Chartland - Garbage Bags - Ragular - 26\" X 36 \"- Clear ",
        "",
        true,
        true,
        true,
        "Chartland - Garbage Bags - Ragular - 26\" X 36 \"- Clear",
      ],
      [
        " Poly Bag - 8 lb - 500/Cs ",
        "assets/PlasticBag/-7886946845839138199.png",
        true,
        true,
        true,
        "Poly Bag - 8 lb - 500/Cs",
      ],
      [
        " Golden Maple - Low Density T - Shirt Bag - White - S57- 500/Cs ",
        "",
        true,
        true,
        true,
        "Golden Maple - Low Density T - Shirt Bag - White - S57- 500/Cs",
      ],
      [
        " Chartland - Garbage Bags - Ex - Strong - 35\" X 47\" - Black ",
        "",
        true,
        true,
        true,
        "Chartland - Garbage Bags - Ex - Strong - 35\" X 47\" - Black",
      ],
      [
        " Golden Maple - 14\"X20\" Produce Rolls - Extra Jumbo ",
        "",
        true,
        true,
        true,
        "Golden Maple - 14\"X20\" Produce Rolls - Extra Jumbo",
      ],
      [
        " Poly Bag - 11 lb - 500/Cs ",
        "assets/PlasticBag/5688525072795361113.png",
        true,
        true,
        true,
        "Poly Bag - 11 lb - 500/Cs",
      ],
      [
        " Chartland - Garbage Bags - Strong - 42\" X 48\" - Black ",
        "",
        true,
        true,
        true,
        "Chartland - Garbage Bags - Strong - 42\" X 48\" - Black",
      ],
      [
        " Poly Bag - 0.5 lb - 500/Cs ",
        "",
        true,
        true,
        true,
        "Poly Bag - 0.5 lb - 500/Cs",
      ],
      [
        " Chartland - Garbage Bags - Ex - Strong - 26\" X 36\" - Clear ",
        "",
        true,
        true,
        true,
        "Chartland - Garbage Bags - Ex - Strong - 26\" X 36\" - Clear",
      ],
      [
        " Golden Maple - Low Density T - Shirt Bag - White - S1 - 2000/Cs ",
        "",
        true,
        true,
        true,
        "Golden Maple - Low Density T - Shirt Bag - White - S1 - 2000/Cs",
      ],
      [
        " Poly Bag - 12 lb - 500/Cs ",
        "assets/PlasticBag/-2889527254735929606.png",
        true,
        true,
        true,
        "Poly Bag - 12 lb - 500/Cs",
      ],
      [
        " Chartland - Garbage Bags - Ex - Strong - 26\" X 36\" - Black ",
        "",
        true,
        true,
        true,
        "Chartland - Garbage Bags - Ex - Strong - 26\" X 36\" - Black",
      ],
      [
        " Poly Bag - 10 lb - 500/Cs ",
        "assets/PlasticBag/-3069903596779347768.png",
        true,
        true,
        true,
        "Poly Bag - 10 lb - 500/Cs",
      ]
    ],
    catImage: [
      ["assets/PlasticBag/4521788198660704861.png", plastic]
    ]
  },
  "Bond or Thermal Paper Roll": {
    data: [
      [
        " Chartland - RR60 - 2.25\"2.7\" (150') - Bond Paper - 50 ct/CS ",
        "",
        true,
        true,
        true,
        "PO#\uff1aRR60",
        "Packing: 50ct/CS",
      ],
      [
        " Chartland - RR72 - 2 1/4\"55' Paper Rolls - Thermal - 100 ct/CS ",
        "assets/BondorThermalPaperRoll/8243204453815857561.png",
        true,
        true,
        true,
        "PO#\uff1aRR72",
        "Packing: 100ct/CS",
      ],
      [
        " Chartland - RR90 - 3 1/8\"180' Paper Rolls - Thermal - 50 ct/CS ",
        "",
        true,
        true,
        true,
        "PO#\uff1aRR90",
        "Packing: 50ct/CS",
      ],
      [
        " Chartland - RR40 - 3\" x 3\" -  2 Ply Yellow/White  - Bond Paper  - 50 ct/CS ",
        "",
        true,
        true,
        true,
        "PO#\uff1aRR40",
        "Packing: 50ct/CS",
      ],
      [
        " Chartland - RR71 - 2 1/4\"75' Paper Rolls - Thermal - 100 ct/CS ",
        "",
        true,
        true,
        true,
        "PO#\uff1aRR71",
        "Pacing: 100ct/CS",
      ],
      [
        " Chartland - RR30 - 3\"3\"(150') - 1 ply - Bond Paper - 50 ct/CS ",
        "",
        true,
        true,
        true,
        "PO#\uff1aRR30",
        "Packing: 50ct/CS",
      ],
      [
        " Chartland - RR20 - 1 7/16\"3\" - Bond Paper - 100ct/CS ",
        "assets/BondorThermalPaperRoll/-8858133851337729496.png",
        true,
        true,
        true,
        "PO#\uff1aRR20",
        "Packing: 100ct/CS",
      ],
      [
        " Chartland - RR10 - 1.75\"3\" - Bond Paper - 100 ct/CS ",
        "",
        true,
        true,
        true,
        "PO#\uff1a RR10",
        "Packing: 100ct/CS",
      ],
      [
        " Chartland - RR70 - 2 1/4\"45'  Paper Rolls - Thermal - 100 ct/CS ",
        "",
        true,
        true,
        true,
        "PO#\uff1aRR70",
        "Packing: 100 ct/CS",
      ],
      [
        " Chartland - RR73 - 2 1/4\"30' Paper Rolls - Thermal - 100 ct/CS ",
        "",
        true,
        true,
        true,
        "PO#\uff1aRR73",
        "Packing: 100ct/CS",
      ],
      [
        " Chartland - RR80 - 2.25\"2.75\" Paper Rolls - Thermal - 50 ct/CS ",
        "",
        true,
        true,
        true,
        "PO#\uff1aRR80",
        "Packing: 50ct/CS",
      ],
      [
        " Chartland - RR74 - 2 1/4\"30' Paper Rolls - Thermal - 50 ct/CS ",
        "",
        true,
        true,
        true,
        "PO#\uff1aRR74",
        "Packing: 50ct/CS",
      ],
      [
        " Chartland - RR50 - 3\"3\" Thermal Rolls - 50 ct/CS ",
        "",
        true,
        true,
        true,
        "PO#\uff1aRR50",
        "Packing: 50ct/CS",
      ]
    ],
    catImage: [
      ["assets/BondorThermalPaperRoll/8243204453815857561.png", thermal]
    ]
  },
  "Napkin": {
    data: [
      [
        " Napkin  -  DN102 - 15\" X 16.5\"-1 Ply - 20 X 150ct ",
        "",
        true,
        true,
        true,
        "Napkin\u00a0 -\u00a0 DN102 - 15\" X 16.5\"-1 Ply - 20 X 150ct.",
        "PO#:: DN102",
      ],
      [
        " Napkin  -  DN401 - 9\" X 9\"-1 Ply - 8 X 500ct ",
        "",
        true,
        true,
        true,
        "Napkin\u00a0 -\u00a0 DN401 - 11\" X 11.4\"-1 Ply - 8 X 500ct",
        "PO#:: DN401",
      ],
      [
        " Napkin  -  DN101 - 7\" X 13.5\"-1 Ply - 20 X 450ct ",
        "",
        true,
        true,
        true,
        "Napkin\u00a0 -\u00a0 DN101 - 7\" X 13.5\"-1 Ply - 20 X 450ct.",
        "PO#:: DN101",
      ],
      [
        " Napkin  -  DN301 - 11\" X 11.4\"-1 Ply - 12 X 450ct ",
        "",
        true,
        true,
        true,
        "Napkin\u00a0 -\u00a0 DN301 - 11\" X 11.4\"-1 Ply - 12 X 450ct",
        "PO#:: DN301",
      ],
      [
        " Napkin  -  DN202 - High Quality - 15\" X 16.5\"-2 Ply  - 20 X 150ct ",
        "",
        true,
        true,
        true,
        "Napkin\u00a0 -\u00a0 DN202 - High Quality - 15\" X 16.5\"-2 Ply\u00a0 - 20 X 150ct",
        "PO#:: DN202",
      ],
      [
        " Napkin  -  DN201 - 15\" X 16.5\"-2 Ply - 20 X 150ct ",
        "",
        true,
        true,
        true,
        "Napkin\u00a0 -\u00a0 DN201 - 15\" X 16.5\"-2 Ply - 20 X 150ct",
        "PO#:: DN201",
      ]
    ],
    catImage: [
      ["assets/PlasticPortionCups/-3375063255935120218.png", napkin]
    ]
  },
  "Plastic Portion cups": {
    "data": [
      [
        " Golden Maple - Plastic Portion Cups - 4oz ",
        "assets/PlasticPortionCups/5900997769936160053.png",
        true,
        true,
        true,
        "PO#\uff1a80009",
      ],
      [
        " Golden Maple - Lid for Plastic Portion Cups - 0.5oz/1oz ",
        "assets/PlasticPortionCups/1246712881998783149.png",
        true,
        true,
        true,
        "PO#\uff1a80010",
      ],
      [
        " Golden Maple - Plastic Portion Cups - 0.5oz ",
        "assets/PlasticPortionCups/-587523794375723107.png",
        true,
        true,
        true,
        "PO#\uff1a80001",
      ],
      [
        " Golden Maple - Plastic Portion Cups - 0.75oz ",
        "assets/PlasticPortionCups/-3484373478168624402.png",
        true,
        true,
        true,
        "PO#\uff1a80002",
      ],
      [
        " Golden Maple - Plastic Portion Cups - 2oz - Black ",
        "",
        true,
        true,
        true,
        "Golden Maple - Plastic Portion Cups - 2oz - Black",
      ],
      [
        " Golden Maple - Plastic Portion Cups - 2.5oz ",
        "assets/PlasticPortionCups/4113997935533645608.png",
        true,
        true,
        true,
        "PO#\uff1a80007",
      ],
      [
        " Golden Maple - Lid for Plastic Portion Cups - 3.25/4oz ",
        "assets/PlasticPortionCups/6864164283713699191.png",
        true,
        true,
        true,
        "PO#\uff1a80012",
      ],
      [
        " Golden Maple - Plastic Portion Cups - 1oz ",
        "assets/PlasticPortionCups/-8694861303300993203.png",
        true,
        true,
        true,
        "PO#\uff1a80003",
      ],
      [
        " Golden Maple - Plastic Portion Cups - 3.25oz ",
        "assets/PlasticPortionCups/-3375063255935120218.png",
        true,
        true,
        true,
        "PO#\uff1a80008",
      ],
      [
        " Golden Maple - Plastic Portion Cups - 2oz ",
        "assets/PlasticPortionCups/-7684952520311844163.png",
        true,
        true,
        true,
        "PO#\uff1a80005",
      ],
      [
        " Golden Maple - Plastic Portion Cups - 1.5oz ",
        "assets/PlasticPortionCups/1967517160198381660.png",
        true,
        true,
        true,
        "PO#\uff1a80004",
      ],
      [
        " Golden Maple - Lid for Plastic Portion Cups - 1.5/2 oz ",
        "assets/PlasticPortionCups/-4955330323063573151.png",
        true,
        true,
        true,
        "PO#\uff1a80011",
      ]
    ],
    catImage: [
      ["assets/PlasticPortionCups/-3375063255935120218.png", portion]
    ]
  },
  "Wood Tableware": {
    data: [
      [
        " Golden Maple-Wood Spoon-20X100 ct ",
        "assets/WoodTableware/5359981813800257678.png",
        true,
        true,
        true,
        "Golden Maple-Wood Spoon-20X100 ct",
      ],
      [
        " Golden Maple-Wood Knife-20X100 ct ",
        "assets/WoodTableware/-7800244617556071764.png",
        true,
        true,
        true,
        "Golden Maple-Wood Knife-20X100 ct",
      ],
      [
        " Golden Maple-Wood Fork 20X100 ct ",
        "assets/WoodTableware/4680064143321107524.png",
        true,
        true,
        true,
        "Golden Maple-Wood Fork 20X100 ct",
      ]
    ],
    catImage: [
      ["assets/WoodTableware/4680064143321107524.png", wood]
    ]
  }
};

Map<String, String> categoryId = {
  "baggage": "Bagasse Products",
  "kraft": "Kraft Paper Fold Box",
  "aluminum": "Aluminum Foil",
  "shopping": "Paper Shopping Bag",
  "coffee": "Paper Coffee cup",
  "soup": "Paper Soup cup",
  "plastic": "Plastic Bags",
  "thermal": "Bond or Thermal Paper Roll",
  "napkin": "Napkin",
  "portion": "Plastic Portion cups",
  "wood": "Wood Tableware",
};

String? valueToID(String value) {
  for (String key in categoryId.keys) {
    if (categoryId[key] == value) {
      return key;
    }
  }
  return null;
}
