// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjSfRPyrQhoEP6ZbHAXO-Mb4DgJi3sjkA',
    appId: '1:328012629085:web:8701d544324f5eb276f9b4',
    messagingSenderId: '328012629085',
    projectId: 'restrosupplyhub',
    authDomain: 'restrosupplyhub.firebaseapp.com',
    storageBucket: 'restrosupplyhub.appspot.com',
    measurementId: 'G-JZ02MPC3J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYG4bXxET9fEeA-H_k5khvax81LhDlJHI',
    appId: '1:328012629085:android:6cf4ab50cb96f4fe76f9b4',
    messagingSenderId: '328012629085',
    projectId: 'restrosupplyhub',
    storageBucket: 'restrosupplyhub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe2_GGk2HVuh5HyHwJ_gc94b-4zOvfXQQ',
    appId: '1:328012629085:ios:97545b3c3e1e9f1276f9b4',
    messagingSenderId: '328012629085',
    projectId: 'restrosupplyhub',
    storageBucket: 'restrosupplyhub.appspot.com',
    iosBundleId: 'com.example.restroSupply',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe2_GGk2HVuh5HyHwJ_gc94b-4zOvfXQQ',
    appId: '1:328012629085:ios:97545b3c3e1e9f1276f9b4',
    messagingSenderId: '328012629085',
    projectId: 'restrosupplyhub',
    storageBucket: 'restrosupplyhub.appspot.com',
    iosBundleId: 'com.example.restroSupply',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjSfRPyrQhoEP6ZbHAXO-Mb4DgJi3sjkA',
    appId: '1:328012629085:web:3be3d39879a3ee0a76f9b4',
    messagingSenderId: '328012629085',
    projectId: 'restrosupplyhub',
    authDomain: 'restrosupplyhub.firebaseapp.com',
    storageBucket: 'restrosupplyhub.appspot.com',
    measurementId: 'G-YWYLQ0798W',
  );
}
